## Makefile.am -- Process this file with automake to produce Makefile.in (to be deployed)
SUBDIRS=mpdecimal-2.4.2 libtommath src
bin_PROGRAMS=M
M_SOURCES=$(src/M*.c)
## replacing: M.c Msession.c Mcolors.c Mshell.c Menvironment.c Mfunctions.c Mlocale.c Mlist.c Marray.c Miterator.c Mtime.c Msystem.c Mvalue.c Mdecimal.c Mrational.c Mbiginteger.c Mexecution.c Mmemory.c Mtoken.c Msettings.c Mjson.c Mstring.c Mchars.c Malloc.c Mmessage.c Moutput.c Mmodule.c
##M_LDADD=@LEXLIB@
dist_doc_DATA=README
