bin_PROGRAMS = M

# the C flags for the M target
M_CFLAGS = -Wno-incompatible-pointer-types -Wno-dangling-else -Wno-incompatible-pointer-types-discards-qualifiers
M_LDFLAGS = -lmpdec -ltommath

M_SOURCES = tommath.h mpdecimal.h Malloc.c Mstring.c Msettings.c Mcolors.c Moutput.c Msession.c Mexpression.c Mmemory.c Mexecution.c Mbiginteger.c Mrational.c Mdecimal.c Mvalue.c Mfunctions.c Menvironment.c M.c
