bin_PROGRAMS = M

# the C flags for the M target
M_CFLAGS = -Wno-incompatible-pointer-types -Wno-dangling-else -Wno-incompatible-pointer-types-discards-qualifiers
M_LDFLAGS =  -L.. -lmpdec -ltommath

M_SOURCES = M.c Menvironment.c Mfunctions.c Mvalue.c Mdecimal.c Mrational.c Mbiginteger.c Mexecution.c Mmemory.c Mexpression.c Msession.c Moutput.c Mcolors.c Msettings.c Mstring.c Malloc.c tommath.h mpdecimal.h
#M_LDADD = mpdecimal-2.4.2/libmpdec/libmpdec.a libtommath/libtommath.a
